### ISSUE TITLE
Add documentation on how to convert a normal folder to repository.

### ISSUE THREAD

**Issue by aSquare14** [aSquare14/Git-Cheat-Sheet#30]
https://stackoverflow.com/questions/3311774/how-to-convert-existing-non-empty-directory-into-a-git-working-directory-and-pus
This might help !
Add it as a new section.

**Comment by Mandelliant** [comment]
@aSquare14 mind if I work on this?

**Comment by aSquare14** [comment]
@Mandelliant Go ahead ! :tada:

**Comment by Mandelliant** [comment]
Addressed in #46

**Comment by vibhavagarwal5** [comment]
Closing this!
