### ISSUE TITLE
Add new git commands

### ISSUE THREAD

**Issue by vibhavagarwal5** [aSquare14/Git-Cheat-Sheet#4]
We want to expand the cheat sheet therefore want your help in adding more and more git commands.

**Comment by vinay72** [comment]
I will like to do it.

**Comment by vibhavagarwal5** [comment]
Closing this for time being..

**Comment by raul1991** [comment]
I would like to add some more commands to the repository that I use on daily basis.

**Comment by vibhavagarwal5** [comment]
@raul1991 pls go ahead. We'll be happy to see you contribute in this repo. 😄

**Comment by raul1991** [comment]
Added some more commands.
